insert into publishers (publisher_name) values ('Berge Inc');
insert into publishers (publisher_name) values ('Kohler LLC');
insert into publishers (publisher_name) values ('Rodriguez and Sons');
insert into publishers (publisher_name) values ('Simonis-O''Kon');
insert into publishers (publisher_name) values ('Gislason-Shields');
insert into publishers (publisher_name) values ('Abbott LLC');
insert into publishers (publisher_name) values ('Connelly-Veum');
insert into publishers (publisher_name) values ('Doyle-Toy');
insert into publishers (publisher_name) values ('Gerlach-Kreiger');
insert into publishers (publisher_name) values ('Nader-Effertz');
insert into publishers (publisher_name) values ('Schultz Inc');
insert into publishers (publisher_name) values ('Kemmer and Sons');
insert into publishers (publisher_name) values ('Gaylord-Harvey');
insert into publishers (publisher_name) values ('Crona and Sons');
insert into publishers (publisher_name) values ('Baumbach, Gottlieb and Kovacek');
insert into publishers (publisher_name) values ('Hilll-Becker');
insert into publishers (publisher_name) values ('Yundt-McClure');
insert into publishers (publisher_name) values ('Johnson-Kling');
insert into publishers (publisher_name) values ('Kreiger, Hirthe and Thiel');
insert into publishers (publisher_name) values ('Trantow-Lesch');
